name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint and Test - ${{ matrix.go-version }}
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint
        run: make lint

      - name: Run Test
        run: make test COVERAGE_PROFILE=coverage.out

      - name: Go Coverage Badge
        if: matrix.platform == 'ubuntu-latest' && matrix.go-version == '1.19.x'
        uses: tj-actions/coverage-badge-go@v1
        with:
          filename: coverage.out

      - name: Verify Changed files
        if: matrix.platform == 'ubuntu-latest' && matrix.go-version == '1.19.x'
        uses: tj-actions/verify-changed-files@v8.1
        id: verify-changed-files
        with:
          files: README.md

      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.files_changed == 'true' && matrix.platform == 'ubuntu-latest' && matrix.go-version == '1.19.x'
        uses: peter-evans/create-pull-request@v3
        with:
          base: "main"
          title: "chore: updated coverage Badge"
          branch: "chore/update-coverage"
          commit-message: "chore: updated coverage Badge"
          body: "updated coverage Badge"
          token: ${{ github.token }}
