name: Lint and Test

on:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    name: Lint and Test - ${{ matrix.go-version }} -  ${{ matrix.platform }}
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Test
        run: make test
      - name: Lint
        run: make lint

      - name: Run Test Coverage
        run: make test-coverage COVERAGE_PROFILE=coverage.out
      - name: Go Coverage Badge
        if: matrix.platform == 'ubuntu-latest' && matrix.go-version == '1.19.x'
        uses: tj-actions/coverage-badge-go@v1
        with:
          filename: coverage.out

      - name: Verify Changed files
        if: matrix.platform == 'ubuntu-latest' && matrix.go-version == '1.19.x'
        uses: tj-actions/verify-changed-files@v8.1
        id: verify-changed-files
        with:
          files: README.md

      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.files_changed == 'true' && matrix.platform == 'ubuntu-latest' && matrix.go-version == '1.19.x'
        uses: peter-evans/create-pull-request@v3
        with:
          base: "main"
          title: "chore: updated coverage Badge"
          branch: "chore/update-coverage"
          commit-message: "chore: updated coverage Badge"
          body: "updated coverage Badge"
          token: ${{ github.token }}
  time_test:
    name: Time tests
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [lint_and_test]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install python deps
        run: pip install -r image_generator/requirements.txt

      - name: Run Time tests
        run: make test-time

      - name: Change graphics for time tests
        uses: siddharth2016/update-readme-image@main
        with:
          IMG_ALT: Time graphics
          HEIGHT: 750px
          WIDTH: 562px
          ALIGN: "-"
